name: Automated Test
on: [push]
jobs:
  automated_test:
    name: Automated Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Produce actual1.txt output
        run: python main.py > actual1.txt
      - name: Comparing output results for test 1
        run: diff expected.txt actual1.txt
      - name: Produce actual2.txt for output
        run: python main.py > actual2.txt
      - name: Comparing output results for test 2
        run: diff expected2.txt actual2.txt
